### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by celsofranssa** [AmenRa/ranx#35]
Hello,
I'd like to determine what query is causing the following error and how to get around it: 
```python
Traceback (most recent call last):
  File "main.py", line 43, in perform_tasks
    eval(params)
  File "main.py", line 25, in eval
    eval_helper.perform_eval()
  File "/home/celso/projects/XMTC-Baselines/source/helper/EvalHelper.py", line 62, in perform_eval
    qrels = Qrels(filtered_relevance_map)
  File "/home/celso/projects/venvs/XMTC-Baselines/lib/python3.8/site-packages/ranx/data_structures/qrels.py", line 62, in __init__
    max_len = max(len(y) for x in doc_ids for y in x)
ValueError: max() arg is an empty sequence
```

My evaluation code is shown in the code snippet below.
```python
ranking = self._retrieve(...)
filtered_relevance_map= {key: value for key, value in self.relevance_map.items() if key in ranking.keys()}
qrels = Qrels(filtered_relevance_map)
run = Run(ranking, name=cls)
result = evaluate(qrels, run, self.metrics, threads=12)
```

**Comment by AmenRa** [comment]
I suspect your `filtered_relevance_map` is not valid.
Can you please post a print of it?

**Comment by celsofranssa** [comment]
> I suspect your `filtered_relevance_map` is not valid. Can you please post a print of it?
`filtered_relevance_map`:
![image](https://user-images.githubusercontent.com/11181748/212191503-35972428-772f-441f-a075-7d941b7f3eba.png)

`ranking`:
![image](https://user-images.githubusercontent.com/11181748/212191653-a78c1af8-1a49-4639-9a40-73b9c99e9c19.png)

**Comment by AmenRa** [comment]
What the code does is simply this:
```python
doc_ids = [list(doc.keys()) for doc in qrels.values()]
max_len = max(len(y) for x in doc_ids for y in x)
```
The code finds the max string length of the doc ids in the dictionary to reduce memory consumption.

You should be able to find the issue by checking what happens with your `filtered_relevance_map` in place of `qrels`.

Please, let me what you find out.

**Comment by AmenRa** [comment]
PS: `doc` variable name in the list comprehension is probably a wrong name. It should be `q` or `query`.

**Comment by celsofranssa** [comment]
> What the code does is simply this:
> 
> ```python
> doc_ids = [list(doc.keys()) for doc in qrels.values()]
> max_len = max(len(y) for x in doc_ids for y in x)
> ```
> 
> The code finds the max string length of the doc ids in the dictionary to reduce memory consumption.
> 
> You should be able to find the issue by checking what happens with your `filtered_relevance_map` in place of `qrels`.
> 
> Please, let me what you find out.

I can't see any problem since I just replaced `doc` with `label` and `query`  with `text` and concatenated it with their ids.

**Comment by AmenRa** [comment]
I can't help you without reproducible code.
The best I can do is guessing.
I never encountered such a problem.

The problem should lay in this line:
```python
doc_ids = [list(doc.keys()) for doc in qrels.values()]
```

`doc.keys()` is probably empty. That should be why the next line throws the exception:

```python
ValueError: max() arg is an empty sequence
```

Have you checked if those two lines of code (isolated from `ranx`) raise the exception?

**Comment by AmenRa** [comment]
Closing for inactivity.
